name: Test Secrets

on:
  workflow_dispatch:

jobs:
  test-secrets:
    name: Test Organization Secrets
    runs-on: ubuntu-latest
    
    steps:
      - name: Test Secret Availability
        run: |
          echo "Testing secret availability (values hidden for security)"
          echo "GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID != '' && 'Available' || 'Missing' }}"
          echo "GCS_BUCKET_SVC_ACCOUNT_JSON_KEY: ${{ secrets.GCS_BUCKET_SVC_ACCOUNT_JSON_KEY != '' && 'Available' || 'Missing' }}"
          echo "GCS_GH_SVC_ACCOUNT_JSON_KEY: ${{ secrets.GCS_GH_SVC_ACCOUNT_JSON_KEY != '' && 'Available' || 'Missing' }}"
          echo "SQLITECLOUD_TIMELINE_CONNECTION_STRING: ${{ secrets.SQLITECLOUD_TIMELINE_CONNECTION_STRING != '' && 'Available' || 'Missing' }}"
